package com.crm.dao.oracle;

import com.crm.pojo.oracle.Emp;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    int deleteByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    Emp selectByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jun 26 18:33:34 CST 2018
     */
    int updateByPrimaryKey(Emp record);
}